spring.cloud.gateway.routes[0].id=greeting-service
spring.cloud.gateway.routes[0].uri=http://greeting-service:9001
spring.cloud.gateway.routes[0].predicates[0]=Path=/greeting,/greeting/**

spring.cloud.gateway.routes[1].id=time-service
spring.cloud.gateway.routes[1].uri=http://time-service:9002
spring.cloud.gateway.routes[1].predicates[0]=Path=/time,/time/**
