apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-canary
  namespace: demo
  labels:
    app: greeting-service
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-service
      track: canary
  template:
    metadata:
      labels:
        app: greeting-service
        track: canary
    spec:
      containers:
        - name: greeting-service
          image: greeting-service:v2
          ports:
            - containerPort: 9001
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 5
