apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todos-deploy
  labels:
    {{- include "todos-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todos
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-todos
    spec:
      containers:
      - name: todos-service
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        ports:
        - containerPort: {{ .Values.app.service.port }}
        resources:
          {{- toYaml .Values.app.resources | nindent 10 }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: SPRING_PROFILES_ACTIVE
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-secret
              key: POSTGRES_PASSWORD
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: {{ .Values.app.service.port }}
          initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: {{ .Values.app.service.port }}
          initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
