apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todos-service
  labels:
    {{- include "todos-app.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-todos
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      {{- if eq .Values.app.service.type "NodePort" }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
  type: {{ .Values.app.service.type }}
