apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    {{- include "todos-app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
