global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'upi-transaction-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['upi-transaction-service:8081']
        labels:
          application: upi-transaction-service
          team: platform-engineering

  - job_name: 'upi-settlement-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['upi-settlement-service:8082']
        labels:
          application: upi-settlement-service
          team: platform-engineering

  - job_name: 'snow-bridge'
    static_configs:
      - targets: ['snow-bridge:5005']
        labels:
          application: snow-bridge
