services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8180
    ports:
      - "8180:8180"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
