
apiVersion: v1
kind: Service
metadata:
  name: todos-service
spec:
  selector:
    app: todos-service-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-service-deploy
  labels:
    app: todos-service-deploy
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-service-pod
  template:
    metadata:
      labels:
        app: todos-service-pod
    spec:
      containers:
      - name: todos-service-container
        image: nagabhushanamn/todos-service:8
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production