
apiVersion: v1
kind: Service
metadata:
  name: todos-service
spec:
  selector:
    app: todos-service-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-service-deploy
  labels:
    app: todos-service-deploy
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-service-pod
  template:
    metadata:
      labels:
        app: todos-service-pod
    spec:
      containers:
      - name: todos-service-container
        image: nagabhushanamn/todos-service:9
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_PROFILES_ACTIVE
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5