apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.greeting.service.type }}
  selector:
    app: greeting-service
  ports:
    - port: {{ .Values.greeting.service.port }}
      targetPort: 9001
