server.port=9002
spring.application.name=time-service
greeting.service.url=http://localhost:9001

grpc.client.greeting-service.address=static://localhost:9090
grpc.client.greeting-service.negotiationType=plaintext
