apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-blue
  namespace: demo
  labels:
    app: greeting-service
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeting-service
      version: blue
  template:
    metadata:
      labels:
        app: greeting-service
        version: blue
    spec:
      containers:
        - name: greeting-service
          image: greeting-service:v1
          ports:
            - containerPort: 9001
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 5
