apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-reader
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeting-sa
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: time-sa
  namespace: demo
