// FoodExpress Order Service -- Jenkinsfile
// BUG: Multiple issues in this pipeline

pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'JDK-17'
    }

    // BUG: No timeout -- builds can hang forever
    // Should have: options { timeout(time: 30, unit: 'MINUTES') }

    environment {
        APP_NAME = 'order-service'
        // BUG: Hardcoded Docker Hub password -- should use credentials()
        DOCKER_USER = 'foodexpress'
        DOCKER_PASSWORD = 'MyD0ck3rP@ssw0rd!'
    }

    stages {
        stage('Checkout') {
            steps {
                // BUG: Building from 'development' branch instead of 'main'
                git branch: 'development',
                    url: 'https://github.com/foodexpress/order-service.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
            // BUG: No archiveArtifacts -- JAR can't be downloaded later
        }

        // BUG: Test stage is completely MISSING!
        // Should have a stage that runs 'mvn test' and publishes junit results
        // This means untested code gets deployed

        stage('Docker Build & Push') {
            steps {
                // BUG: Image tagged as 'latest' only -- non-reproducible
                sh "docker build -t ${DOCKER_USER}/${APP_NAME}:latest ."
                // BUG: Using hardcoded password for docker login
                sh "echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin"
                sh "docker push ${DOCKER_USER}/${APP_NAME}:latest"
            }
        }

        stage('Deploy to Staging') {
            steps {
                sh """
                    ssh deploy@staging-server \
                      'docker pull ${DOCKER_USER}/${APP_NAME}:latest && \
                       docker compose -f /opt/foodexpress/docker-compose.yml up -d order-service'
                """
            }
        }
    }

    // BUG: No post section at all
    // Missing: failure notification, workspace cleanup, success message
}
