#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"

echo "=== Helm & Kustomize Demo ==="
echo ""
echo "--- Option 1: Helm ---"
echo ""

echo "Deploy DEV:"
echo "  helm install demo-dev $BASE_DIR/helm/demo-chart -f $BASE_DIR/helm/demo-chart/values-dev.yaml"
echo ""
echo "Deploy PROD:"
echo "  helm install demo-prod $BASE_DIR/helm/demo-chart -f $BASE_DIR/helm/demo-chart/values-prod.yaml"
echo ""
echo "Upgrade:"
echo "  helm upgrade demo-dev $BASE_DIR/helm/demo-chart -f $BASE_DIR/helm/demo-chart/values-dev.yaml --set greeting.message='Updated!'"
echo ""
echo "Rollback:"
echo "  helm rollback demo-dev 1"
echo ""
echo "Uninstall:"
echo "  helm uninstall demo-dev"
echo "  helm uninstall demo-prod"

echo ""
echo "--- Option 2: Kustomize ---"
echo ""
echo "Preview DEV:"
echo "  kubectl kustomize $BASE_DIR/kustomize/overlays/dev"
echo ""
echo "Deploy DEV:"
echo "  kubectl apply -k $BASE_DIR/kustomize/overlays/dev"
echo ""
echo "Deploy PROD:"
echo "  kubectl apply -k $BASE_DIR/kustomize/overlays/prod"
echo ""
echo "Delete:"
echo "  kubectl delete -k $BASE_DIR/kustomize/overlays/dev"
echo "  kubectl delete -k $BASE_DIR/kustomize/overlays/prod"
