spring.application.name=api-gateway
server.port=8181

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Route to foo-service: /foo/** -> foo-service/**
spring.cloud.gateway.server.webflux.routes[0].id=foo-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://foo-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/foo/**

# Route to bar-service: /bar/** -> bar-service/**
spring.cloud.gateway.server.webflux.routes[1].id=bar-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://bar-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/bar/**
