apiVersion: v1
kind: Pod
metadata:
  name: nfs-demo
spec:
  containers:
  - name: logger
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Logging to NFS' >> /mnt/logs/app.log && sleep 3600"]
    volumeMounts:
    - mountPath: "/mnt/logs"
      name: logs-storage

  volumes:
  - name: logs-storage
    nfs:
      server: 10.160.0.11
      path: "/psi/log"
