

# H2 datasource configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Thymeleaf template location
spring.thymeleaf.prefix=classpath:/template/