apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: greeting-service
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30001
