server:
  port: 8082

spring:
  application:
    name: upi-settlement-service

upi:
  transaction-service-url: http://upi-transaction-service:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: upi-settlement-service
