services:
  order-service:
    build: ./order-service
    ports:
      - "3000:3000"
    environment:
      - PAYMENT_SERVICE_URL=http://payment-service:8080
    depends_on:
      - payment-service

  payment-service:
    build: ./payment-service
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - order-service
      - payment-service

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
