spring.application.name=time-service
server.port=9002
jwt.secret=ThisIsAVeryLongSecretKeyForHMACSHA256SigningThatMustBeAtLeast256Bits!
greeting.service.url=http://localhost:9001
management.endpoints.web.exposure.include=health
